### ISSUE TITLE
Workaround to package include induced source control problems?

### ISSUE THREAD

**Issue by ccruden-shookiot** [aliencube/AzureFunctions.Extensions#106]
Is there a way to nicely modify the default scaffolding included with A.A.E.OpenApi so that it sticks and is source-controllable?

Specifically, A.A.E.OpenApi adds three files (IOpenApiHttpTriggerContext.cs, OpenApiHttpTrigger.cs, and OpenApiHttpTriggerContext.cs) to the Azure function project. The triggers it defines are created with AuthorizationLevel.Function by default, and we'd like to build with AuthorizationLevel.Anonymous. Changing the files is easy enough, but because they're autogenerated by the package they're in a directory outside our source control tree, so unless everyone (and the build system) makes the same changes, the project won't build properly. Visual Studio won't let you delete the files from the project so you can't substitute your own classes/triggers. The classes themselves don't seem to be overridable, so you can't substitute your own code to change their behaviour. You can define ExcludeRestorePackageImports in the main project file to prevent the files from being included in the build, but this then strips a bunch of other autogenerated build defines that are required for building the project.

Is there a procedure that's meant to be used here that I'm missing? How do I change the behaviour of these auto-generated files in a way that can be checked into source control so other people can build the project successfully?

**Comment by SimonKoegler** [comment]
As a workaround I installed [Aliencube.AzureFunctions.Extensions.OpenApi.Core](https://github.com/aliencube/AzureFunctions.Extensions/blob/dev/docs/openapi-core.md) instead of [Aliencube.AzureFunctions.Extensions.OpenApi](https://github.com/aliencube/AzureFunctions.Extensions/blob/dev/docs/openapi.md) and added those three files manually (from https://github.com/aliencube/AzureFunctions.Extensions/tree/master/templates/OpenApiEndpints) so the change to AuthorizationLevel.Anonymous can be commited to source control.

**Comment by ccruden-shookiot** [comment]
Thanks Simon! For some reason that did not occur to me, and it does indeed get around the problem.

**Comment by justinyoo** [comment]
@ccruden-shookiot Oops it's too late to answer! Yes, as @SimonKoegler's suggestion is what I was going to offer for now.
