### ISSUE TITLE
Enums as strings

### ISSUE THREAD

**Issue by OskarNet** [aliencube/AzureFunctions.Extensions#75]
Hi

Will there be a way for us to show enum values as strings in the document?

**Comment by justinyoo** [comment]
@OskarNet Thanks for your comment! Is it the same issue as #81 ? Where exactly does your problem occur?

**Comment by OskarNet** [comment]
Thanks for your answer. Yes that seems to be the same problem.  Would be good if this got fixed :)

**Comment by justinyoo** [comment]
I have an enum in the request/response payload, and it's working.

![image](https://user-images.githubusercontent.com/1538528/86100097-5ab74180-baf3-11ea-9cd1-126b3809bf5f.png)

https://github.com/aliencube/Social-Media-Integration-Suite/blob/0e2d10cbcd8868021292f6bdec98b5c52327de51/src/FeedReaders/Models/FeedSource.cs#L9

Can you apply this approach on your app so that it solves the issue?

**Comment by OskarNet** [comment]
After switching to Newtonssoft and adding the attributes to the enum itself and not the enum property in the model it works.
Thanks Justin
