### ISSUE TITLE
Data annotations

### ISSUE THREAD

**Issue by OskarNet** [aliencube/AzureFunctions.Extensions#76]
Hi 

Will it be possible to use data annotations like [Required] to identify properties that are requried for the document?

**Comment by Svalhansen** [comment]
Along these lines usually swagger respects JsonProperty of form 

[JsonProperty("foo")]
public string MyProperty {get; set;}

This makes the serialisation / deserialization and swagger contract in sync. 
This does not seem to be the case for this implementation where it uses the property name in the swagger document. 

So in the above example the swagger doc would generate a request sending "MyProperty" where as the JsonSerializer (newtonsoft) would be looking for "foo". 

Atleast this construct is common in other swagger project types since it would make the naming stay fixed even if renaming/refactoring a DTO property name.

It seems there swagger generated only does camel case transformation of property names

**Comment by OskarNet** [comment]
I see. My issue is that the attribute OpenApiRequestBody doesn't offer a way of marking certain properties as required in the Swagger document.
[OpenApiRequestBody(StringConstants.JsonContentType, typeof(MyModell))]

**Comment by justinyoo** [comment]
@OskarNet @Svalhansen This has been fixed on [v3.0.0](https://www.nuget.org/packages/Aliencube.AzureFunctions.Extensions.OpenApi/3.0.0). More details can be found at [openapi-core.md](https://github.com/aliencube/AzureFunctions.Extensions/blob/dev/docs/openapi-core.md#supported-jsonnet-decorators)
